const constants = {
  EMAIL_IS_REQUIRED: 'Email is required',
  INVALID_PASSWORD_LENGTH: 'Password must be at least 8 characters',
  USER_ALREADY_EXISTS: 'User already exists',
  SERVER_AUTH_MISCONFIGURED: 'Server auth misconfigured',
  UNAUTHORIZED: 'Unauthorized',
  EMAIL_AND_PASSWORD_REQUIRED: 'Email and password are required',
  INVALID_CREDENTIALS: 'Invalid credentials',
  INTERNAL_SERVER_ERROR: 'Internal server error',
  CURRENT_PASSWORD_INCORRECT: 'Current password is incorrect',
  CURRENT_AND_NEW_PASSWORD_REQUIRED: 'Current and new password are required',
  CURRENT_AND_NEW_PASSWORD_MUST_BE_DIFFERENT: 'Current and new passwords must be different',
  COLLECTION_NAME_REQUIRED: 'Collection name is required',
  COLLECTION_NOT_FOUND: 'Collection not found',
  INVALID_DASHBOARD_ID: 'Invalid dashboard ID',
  DASHBOARD_NOT_FOUND: 'Dashboard not found',
  INVALID_DASHBOARD_ID: 'Invalid dashboard ID',
  SHARES_MUST_BE_A_NON_EMPTY_ARRAY: 'Shares must be a non-empty array',
  CSV_MUST_HAVE_AT_LEAST_A_HEADER_AND_ONE_DATA_ROW:
    'CSV must have at least a header and one data row',
  ONLY_EDITORS_CAN_SHARE: 'Only editors can share',
  CANNOT_SAVE_DASHBOARD: 'Cannot save this dashboard',
  ONLY_OWNER_CAN_SYNC_SHARED_CHANGES: 'Only the owner can sync shared changes',
  DASHBOARD_LINEAGE_NOT_FOUND: 'Dashboard lineage not found',
  FILE_CONTENT_REQUIRED: 'File content is required',
  UNSUPPORTED_FILE_TYPE: 'Invalid file format. Supported files: CSV, JSON, XLSX',
  INVALID_FILE_FORMAT: 'Invalid file format',
  FILE_IS_EMPTY: 'File is empty',
  UNABLE_TO_PARSE_FILE: 'Unable to parse file',
  FILE_TOO_LARGE: 'File is too large',
  UNSUPPORTED_FILE_STRUCTURE: 'Unsupported file structure',
  EXCEL_FILE_HAS_NO_SHEETS: 'Excel file has no sheets',
  EXCEL_FIRST_SHEET_EMPTY: 'Excel first sheet is empty',
  NO_VALID_DATA_FOUND_IN_FILE: 'No valid data found in file',
  FAILED_TO_PARSE_FILE: 'Failed to parse file',
  SESSION_EXPIRED: 'Session expired',
  EXPIRES_IN_DAYS: '7d',
  FILE_UPLOAD_NEW: (collName, count) =>
    `Uploaded ${count} records into new collection '${collName}'`,
  FILE_UPLOAD_REPLACED: (collName, count) =>
    `Replaced collection '${collName}' with ${count} records`,
};

export default constants;
